In [7]:
import torch
import os
import pandas as pd
from torch.utils.data import DataLoader, Dataset

from datasets import ComplexDataset_train, collate_fn_train
from utils import preprocess_train


folder_path = "../../data/trainset/"
data, labels = preprocess_train(folder_path)

# 创建测试数据集实例
test_dataset = ComplexDataset_train(data, labels)

# 构建test_loader
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False, collate_fn=collate_fn_train)

# 加载模型
model_path = '../../checkpoint/model_9055.pth'  # 替换为你的模型路径
model = torch.load(model_path, map_location='cpu')
model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# 假设test_loader用于加载无标签的测试数据
predictions = 0

with torch.no_grad():
    for inputs, targets in test_loader:
        inputs = inputs.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)  # 获取最大概率的类别索引作为预测结果
        if preds.cpu() != targets:
            print(f"target:{targets}")
            print(torch.nn.functional.softmax(outputs.cpu()))
            predictions += 1
print(predictions)


target:tensor([3])
tensor([[1.7161e-05, 1.5689e-07, 5.5505e-05, 2.4804e-01, 6.1117e-05, 2.7007e-01,
         1.0868e-04, 2.6007e-01, 2.2155e-01, 3.4644e-05, 4.3299e-07]])
target:tensor([5])
tensor([[8.2350e-02, 4.6225e-04, 1.2642e-01, 8.7283e-02, 8.5365e-02, 8.8346e-02,
         2.4752e-01, 1.0214e-01, 9.6986e-02, 8.3094e-02, 3.0283e-05]])
target:tensor([3])
tensor([[2.8323e-01, 5.8824e-05, 8.0407e-02, 1.5263e-01, 1.0452e-01, 1.1353e-01,
         2.1385e-01, 1.5530e-02, 1.8065e-02, 1.8171e-02, 2.7203e-06]])
target:tensor([7])
tensor([[1.1454e-01, 1.0446e-05, 1.2885e-01, 7.2606e-02, 1.0226e-01, 7.1690e-02,
         1.7953e-01, 8.0478e-02, 9.8958e-02, 1.5108e-01, 8.3355e-07]])


/tmp/ipykernel_3510233/2078637077.py:37: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(torch.nn.functional.softmax(outputs.cpu()))


target:tensor([3])
tensor([[2.1318e-01, 1.4507e-03, 3.9449e-02, 1.3980e-01, 1.1898e-01, 8.8981e-02,
         2.9927e-01, 4.8860e-02, 4.6701e-02, 3.3205e-03, 8.7373e-06]])
target:tensor([7])
tensor([[1.7523e-04, 5.6871e-06, 4.7414e-04, 2.5016e-01, 4.7744e-04, 2.6925e-01,
         8.1244e-04, 2.4986e-01, 2.2838e-01, 3.9427e-04, 9.9107e-06]])
target:tensor([10])
tensor([[1.8755e-02, 7.3356e-08, 9.9719e-07, 5.3588e-02, 1.1977e-06, 4.5604e-03,
         1.5937e-07, 7.6173e-01, 8.3628e-06, 4.0676e-04, 1.6095e-01]])
target:tensor([5])
tensor([[0.1076, 0.2573, 0.1340, 0.0118, 0.1452, 0.0538, 0.0582, 0.0557, 0.0671,
         0.1079, 0.0016]])
target:tensor([4])
tensor([[6.5059e-02, 4.8786e-04, 1.3387e-01, 9.5103e-02, 1.0131e-01, 6.0348e-02,
         2.3291e-01, 1.0017e-01, 1.1262e-01, 9.8106e-02, 2.1610e-05]])
target:tensor([7])
tensor([[7.0324e-02, 4.6437e-05, 7.7629e-02, 8.4552e-02, 7.7944e-02, 9.3274e-02,
         2.9750e-01, 9.4416e-02, 5.6832e-02, 1.4748e-01, 3.0095e-06]])
target:tensor([5]